name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install XcodeGen
        run: |
          brew install xcodegen
      - name: Install xcpretty
        run: |
          gem install xcpretty --no-document
      - name: Generate Xcode project
        run: |
          xcodegen generate
      - name: Build iOS app (no signing)
        run: |
          xcodebuild -project ChimeraCoach.xcodeproj -scheme ChimeraCoach -sdk iphonesimulator -configuration Debug CODE_SIGNING_ALLOWED=NO build | xcpretty
        shell: bash
      - name: Done
        run: echo "Build finished"
